version: '3.8'

services:
  ui-backend:
    build: ./ui-backend
    ports:
      - "5000:5000"
    depends_on:
      - ai-backend
    networks:
      - detection-network
    volumes:
      - ./ui-backend/uploads:/app/uploads

  ai-backend:
    build: ./ai-backend
    ports:
      - "5001:5001"
    networks:
      - detection-network
    volumes:
      - ./ai-backend/outputs:/app/outputs
      - ./ai-backend/models:/app/models

networks:
  detection-network:
    driver: bridge